### ISSUE TITLE
error on raspberry pi

### ISSUE THREAD

**Issue by toshibochan** [planetbeing/homebridge-foscam-ng#3]
error on raspberry pi

"      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'Foscam-NG' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:106:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:263:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:71:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)"

**Comment by planetbeing** [comment]
I believe this is caused if the module is not installed globally. Did you try 

`sudo npm install -g homebridge-foscam-ng`

If you get errors related to the "bindings file" in the Homebridge log after installing it this way, try:

`sudo npm install -g --unsafe-perm homebridge-foscam-ng`

Finally, make sure you're using Node 6.6.0 or greater.
